version: "3.9"

services:
  bob:
    build: .
    volumes:
      - ./bobweb/web/db.sqlite3:/bobweb/web/db.sqlite3
    restart: always
    environment:
      COMMIT_MESSAGE: ${COMMIT_MESSAGE}
      COMMIT_AUTHOR_NAME: ${COMMIT_AUTHOR_NAME}
      COMMIT_AUTHOR_EMAIL: ${COMMIT_AUTHOR_EMAIL}
      BOT_TOKEN: ${BOT_TOKEN}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      OPEN_WEATHER_API_KEY: ${OPEN_WEATHER_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      TG_CLIENT_API_ID: ${TG_CLIENT_API_ID}
      TG_CLIENT_API_HASH: ${TG_CLIENT_API_HASH}
  web:
    build: .
    volumes:
      - ./bobweb/web/db.sqlite3:/bobweb/web/db.sqlite3
      - ./bobweb/web/staticfiles:/bobweb/web/staticfiles
    restart: always
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
    expose:
      - "8000"
    working_dir: /bobweb/web
    command: python manage.py runserver
