services:
  bob:
    build: .
    volumes:
      - ./web/db.sqlite3:/web/db.sqlite3
    restart: always
    env_file:
      - .env
    environment:
      COMMIT_MESSAGE: ${COMMIT_MESSAGE}
      COMMIT_AUTHOR_NAME: ${COMMIT_AUTHOR_NAME}
      COMMIT_AUTHOR_EMAIL: ${COMMIT_AUTHOR_EMAIL}
      BOT_TOKEN: ${BOT_TOKEN}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      OPEN_WEATHER_API_KEY: ${OPEN_WEATHER_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      TG_CLIENT_API_ID: ${TG_CLIENT_API_ID}
      TG_CLIENT_API_HASH: ${TG_CLIENT_API_HASH}
      TWITCH_CLIENT_ID: ${TWITCH_CLIENT_ID}
      TWITCH_CLIENT_SECRET: ${TWITCH_CLIENT_SECRET}
      ENTSOE_API_KEY: ${ENTSOE_API_KEY}
  web:
    build: .
    volumes:
      - ./web/db.sqlite3:/web/db.sqlite3
      - ./web/staticfiles:/web/staticfiles
    restart: always
    env_file:
      - .env
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
    expose:
      - "8000"
    working_dir: /web
    command: python manage.py runserver
