# Generated by Django 4.0.1 on 2022-01-21 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, null=True)),
                ('latestLeet', models.DateField(null=True)),
                ('messageCount', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Proverb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proverb', models.TextField(unique=True)),
                ('author', models.CharField(max_length=255, null=True)),
                ('date_created', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nick', models.CharField(max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remember_this', models.TextField()),
                ('date_when_reminded', models.DateTimeField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bobapp.chat')),
            ],
            options={
                'ordering': ['date_when_reminded'],
            },
        ),
        migrations.CreateModel(
            name='ChatMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestige', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('admin', models.BooleanField(default=False)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bobapp.chat')),
                ('tg_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bobapp.telegramuser')),
            ],
            options={
                'ordering': ['-rank', '-prestige'],
                'unique_together': {('chat', 'tg_user')},
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='members',
            field=models.ManyToManyField(through='bobapp.ChatMember', to='bobapp.TelegramUser'),
        ),
        migrations.CreateModel(
            name='ChatProverb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_appearances', models.PositiveIntegerField(default=0)),
                ('last_appeared', models.DateTimeField(null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bobapp.chat')),
                ('proverb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bobapp.proverb')),
            ],
            options={
                'ordering': ['last_appeared'],
                'unique_together': {('chat', 'proverb')},
            },
        ),
    ]
