# Generated by Django 4.0.1 on 2022-01-21 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bobapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='latestLeet',
            new_name='latest_leet',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='messageCount',
            new_name='message_count',
        ),
    ]
