# Generated by Django 4.0.1 on 2022-01-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobapp', '0002_rename_latestleet_chat_latest_leet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='message_count',
        ),
        migrations.AddField(
            model_name='chatmember',
            name='message_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
