# Generated by Django 4.0.1 on 2022-01-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobapp', '0004_rename_nick_telegramuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='broadcast_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
