# Generated by Django 4.0.1 on 2022-01-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobapp', '0005_chat_broadcast_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bob',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uptime_started_date', models.DateField(null=True)),
                ('latest_startup_broadcast_message', models.TextField(null=True)),
            ],
        ),
    ]
