# Generated by Django 4.0.1 on 2022-01-28 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bobapp', '0006_bob'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='latest_promotion_from_git_commit',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='bob',
            name='uptime_started_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='GitUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('tg_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bobapp.telegramuser')),
            ],
            options={
                'unique_together': {('name', 'email')},
            },
        ),
    ]
