# Generated by Django 4.0.1 on 2022-01-29 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bobapp', '0007_telegramuser_latest_promotion_from_git_commit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bob',
            name='global_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bobapp.telegramuser'),
        ),
    ]
