# Generated by Django 4.0.1 on 2022-01-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobapp', '0008_bob_global_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gituser',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gituser',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
