# Generated by Django 4.0.1 on 2022-01-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobapp', '0010_alter_gituser_email_alter_gituser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gituser',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
