# Generated by Django 4.0.1 on 2022-02-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobapp', '0012_alter_gituser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmember',
            name='latest_weather_city',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
