# Generated by Django 4.0.1 on 2022-02-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobapp', '0015_alter_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='huutista_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='or_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
