# Generated by Django 4.0.1 on 2022-05-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobapp', '0016_chat_huutista_enabled_chat_or_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='ruoka_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
