# Generated by Django 4.1.6 on 2023-02-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bobapp', '0019_chat_free_game_offers_enabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmember',
            options={'ordering': ['-rank', '-prestige', '-message_count']},
        ),
    ]
