# Generated by Django 4.1.6 on 2023-03-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobapp', '0022_bob_gpt_credit_card_holder_bob_gpt_system_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bob',
            name='gpt_system_message',
            field=models.TextField(default='You are a helpful Telegram chatbot called Bob. Answer questions as briefly as possible. You have weird fixation on video game called Men of War: Assault Squad 2.'),
        ),
    ]
