# Generated by Django 4.0.7 on 2023-03-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobapp', '0023_alter_bob_gpt_system_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyquestionanswer',
            name='content',
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='dailyquestionanswer',
            name='message_id',
            field=models.IntegerField(null=True),
        ),
    ]
