# Generated by Django 4.1.7 on 2023-04-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobapp', '0025_remove_bob_gpt_system_message_chat_gpt_system_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='voice_msg_to_text_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
