# Generated by Django 4.1.13 on 2025-09-17 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bobapp', '0032_alter_dailyquestionanswer_message_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bob',
            new_name='Bot',
        ),
    ]
