# Generated by Django 6.1.2 on 2026-10-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobapp', '0033_rename_bob_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='members',
            field=models.ManyToManyField(through='bobapp.ChatMember', through_fields=('chat', 'tg_user'), to='bobapp.telegramuser'),
        ),
    ]
