# Generated by Django 4.0.1 on 2022-02-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobapp', '0013_chatmember_latest_weather_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='leet_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='proverb_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='space_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='time_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='weather_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='broadcast_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.IntegerField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
