# Generated by Django 4.0.8 on 2022-10-07 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bobapp', '0017_chat_ruoka_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuestion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('update_id', models.IntegerField()),
                ('content', models.CharField(max_length=4096)),
            ],
            options={
                'db_table': 'bobapp_daily_question',
            },
        ),
        migrations.CreateModel(
            name='DailyQuestionSeason',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('season_number', models.IntegerField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bobapp.chat')),
            ],
            options={
                'db_table': 'bobapp_daily_question_season',
                'unique_together': {('id', 'chat', 'season_number', 'start_datetime', 'end_datetime')},
            },
        ),
        migrations.CreateModel(
            name='DailyQuestionAnswer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('update_id', models.IntegerField()),
                ('content', models.CharField(max_length=4096)),
                ('is_winning_answer', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bobapp.dailyquestion')),
                ('update_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_question_answers', to='bobapp.telegramuser')),
            ],
            options={
                'db_table': 'bobapp_daily_question_answer',
            },
        ),
        migrations.AddField(
            model_name='dailyquestion',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bobapp.dailyquestionseason'),
        ),
        migrations.AddField(
            model_name='dailyquestion',
            name='update_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_questions', to='bobapp.telegramuser'),
        ),
        migrations.AddConstraint(
            model_name='dailyquestionanswer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_winning_answer', True)), fields=('question', 'is_winning_answer'), name='unique_is_winning_answer'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyquestionanswer',
            unique_together={('question', 'update_author')},
        ),
        migrations.AlterUniqueTogether(
            name='dailyquestion',
            unique_together={('datetime', 'season')},
        ),
    ]
