# Generated by Django 4.0.7 on 2022-09-19 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bobapp', '0017_chat_ruoka_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuestionSeason',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('season_number', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bobapp.chat')),
            ],
            options={
                'db_table': 'bobapp_daily_question_season',
                'unique_together': {('chat', 'season_number', 'start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='DailyQuestion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('update_id', models.IntegerField()),
                ('content', models.CharField(max_length=4096)),
                ('reply_count', models.IntegerField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bobapp.dailyquestionseason')),
                ('winner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bobapp.telegramuser')),
            ],
            options={
                'db_table': 'bobapp_daily_question',
                'unique_together': {('date', 'season')},
            },
        ),
    ]
