# Generated by Django 4.0.7 on 2022-09-26 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bobapp', '0017_chat_ruoka_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuestionSeason',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('season_number', models.IntegerField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bobapp.chat')),
            ],
            options={
                'db_table': 'bobapp_daily_question_season',
                'unique_together': {('id', 'chat', 'season_number', 'start_datetime', 'end_datetime')},
            },
        ),
        migrations.CreateModel(
            name='DailyQuestion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('update_id', models.IntegerField()),
                ('content', models.CharField(max_length=4096)),
                ('reply_count', models.IntegerField(default=0)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bobapp.dailyquestionseason')),
                ('update_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_questions', to='bobapp.telegramuser')),
                ('winner_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_question_wins', to='bobapp.telegramuser')),
            ],
            options={
                'db_table': 'bobapp_daily_question',
                'unique_together': {('datetime', 'season')},
            },
        ),
    ]
