# Generated by Django 4.0.7 on 2023-01-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobapp', '0018_dailyquestion_dailyquestionseason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='message_board_msg_id',
            field=models.IntegerField(null=True),
        ),
    ]
