# Generated by Django 4.0.7 on 2023-03-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobapp', '0020_alter_chatmember_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='nordpool_graph_width',
            field=models.IntegerField(null=True),
        ),
    ]
