# Generated by Django 4.1.7 on 2023-04-04 17:04

from django.db import migrations, models

from bobweb.web.bobapp.models import Bob, Chat


# We can't import models directly as they may be in newer
# version than this migration expects. We use the historical version.

def migrate_old_gpt_system_prompt_to_new(apps, schema_editor):
    bob: Bob = apps.get_model('bobapp', 'bob').objects.first()
    if bob is None:
        return
    Chat: models.Model = apps.get_model('bobapp', 'chat')
    for chat in Chat.objects.all():
        if chat.id in [-1001088846469, 240648043]:
            chat.gpt_system_prompt = bob.gpt_system_message


def migrate_new_system_prompt_back_to_old(apps, schema_editor):
    bob: Bob = apps.get_model('bobapp', 'bob').objects.first()
    if bob is None:
        return
    # Set global gpt system message from bob chat
    chat: Chat = apps.get_model('bobapp', 'chat').objects.filter(id=-1001088846469)
    bob.gpt_system_message = chat.gpt_system_prompt


class Migration(migrations.Migration):

    dependencies = [
        ('bobapp', '0024_alter_dailyquestionanswer_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bob',
            name='gpt_system_message',
        ),
        migrations.AddField(
            model_name='chat',
            name='gpt_system_prompt',
            field=models.TextField(null=True),
        ),
        migrations.RunPython(code=migrate_old_gpt_system_prompt_to_new,
                             reverse_code=migrate_new_system_prompt_back_to_old)
    ]
