# Generated by Django 4.1.6 on 2023-04-12 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bobapp', '0025_remove_bob_gpt_system_message_chat_gpt_system_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proverb',
            name='author',
        ),
        migrations.AddField(
            model_name='proverb',
            name='tg_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bobapp.telegramuser'),
        ),
    ]
