# Generated by Django 4.1.5 on 2023-05-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobapp', '0026_chat_voice_msg_to_text_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='quick_system_prompts',
            field=models.JSONField(null=True),
        ),
    ]
