# Generated by Django 4.1.7 on 2023-05-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobapp', '0026_chat_voice_msg_to_text_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyquestionanswer',
            name='content',
            field=models.CharField(blank=True, default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='dailyquestionanswer',
            name='message_id',
            field=models.IntegerField(),
        ),
    ]
