# Generated by Django 4.1.5 on 2023-05-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobapp', '0027_alter_dailyquestionanswer_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='quick_system_prompts',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
