# Generated by Django 4.1.5 on 2023-05-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobapp', '0027_chat_quick_system_prompts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='quick_system_prompts',
            field=models.JSONField(default={}, null=True),
        ),
    ]
