# Generated by Django 4.1.7 on 2023-07-20 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bobapp', '0028_chat_quick_system_prompts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyquestion',
            name='question_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_question', to='bobapp.telegramuser'),
        ),
        migrations.AlterField(
            model_name='dailyquestionanswer',
            name='answer_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='daily_question_answer', to='bobapp.telegramuser'),
        ),
        migrations.AlterField(
            model_name='dailyquestionseason',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='daily_question_season', to='bobapp.chat'),
        ),
    ]
