# Generated by Django 4.1.5 on 2023-05-19 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bobapp', '0027_alter_dailyquestionanswer_content_and_more'),
        ('bobapp', '0029_alter_chat_quick_system_prompts'),
    ]

    operations = [
    ]
