# Generated by Django 4.1.13 on 2024-01-08 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bobapp', '0029_alter_dailyquestion_question_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bob',
            name='error_log_chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bobapp.chat'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='broadcast_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
