# Generated by Django 4.1.13 on 2024-01-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobapp', '0030_bob_error_log_chat_alter_chat_broadcast_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='message_board_msg_id',
            field=models.IntegerField(null=True),
        ),
    ]
