rules = {
    1: "Kun olet saanut heidän rahansa, älä koskaan anna niitä takaisin.",
    2: "Parhaasta sopimuksesta  tulee eniten voittoa.",
    3: "Älä koskaan maksa enempää kuin mitä tarve vaatii.",
    4: "Nainen, jolla on vaatteet, on kuin keittiössä oleva mies.",
    6: "Älä koskaan anna perheen tulla voittojen tielle",
    7: "Pidä korvasi kuulolla.",
    8: "Pienellä painettu teksti tietää suurta riskiä.",
    9: "Otollinen tilaisuus ja vaisto on yhtä kuin voitto.",
    10: "Ahneus on ikuista.",
    11: "Vaikka se olisi ilmainen, voit silti ostaa sen halvemmalla.",
    12: "Kaikki mikä on myymisen arvoista, on myymisen arvoista kahteen kertaan.",
    13: "Kaikki mikä on tekemisen arvoista, on tekemisen arvoista rahaa vastaan.",
    16: "Diili on diili.",
    17: "Sopimus on sopimus on sopimus, mutta vain ferengien välillä.",
    18: "Ferengi ilman voittoa ei ole ferengi.",
    19: "Ei tyytyväisyystakuuta.",
    21: "Älä koskaan laita ystävyyttä voittojen edelle.",
    22: "Viisas mies voi kuulla voiton tuulessa.",
    23: "Mikään ei ole tärkeämpää kuin terveytesi. Paitsi rahasi.",
    24: "Latinumilla ei voi ostaa onnellisuutta, mutta sillä voi totisesti vuokrata sitä.",
    25: "Kuolleena ei voi käydä kauppaa.",
    27: "Ei ole mitään vaarallisempaa kuin rehellinen liikemies.",
    31: "Älä koskaan pilkkaa ferengin äitiä, vaan pilkkaa sen sijaan jotain, jolla on hänelle merkitystä.",
    33: "Pomon miellyttäminen ei ole koskaan pahasta.",
    34: "Sota on hyvää bisnekselle... mutta vain silloin kun se tapahtuu kaukana. Mitä lähempänä se on, "
         "sitä huonompaa bisnes on.",
    35: "Rauha on hyvää bisnekselle.",
    40: "Voit antaa naisen koskea korvanlehtiisi, mutta et koskaan latinumiisi.",
    41: "Voitto on itseisarvo.",
    44: "Älä koskaan sekoita viisautta tuuriin.",
    45: "Kasva tai kuole.",
    52: "Älä koskaan pyydä, jos voit ottaa.",
    57: "Hyvät asiakkaat ovat harvinaisia kuin latinumi. Vaali niitä.",
    58: "Menestykselle ei ole korviketta.",
    59: "Ilmaiset neuvot ovat harvoin halpoja.",
    60: "Pidä valheesi johdonmukaisina.",
    62: "Mitä vaarallisempi reitti, sen suurempi voitto.",
    65: "Tulipa voittoa tai tappiota, voit aina ottaa Hupyrianin kuoriaisnuuskaa.",
    74: "Tieto on voittoa.",
    75: "Koti on siellä missä sydän on, mutta tähdet on tehty latinumista.",
    76: "Julista silloin tällöin rauha. Se saa vihollisesi aivan pyörälle päästään!",
    77: "Jos rikot sen, joudut maksamaan sen.",
    79: "Varo vulkaanien tiedonjanoa.",
    82: "Mitä köykäisempi tuote, sen korkeampi hinta.",
    85: "Älä anna kilpailijoiden tietää, mitä ajattelet.",
    89: "Älä kysy mitä voitot voivat tehdä sinun eteesi, vaan mitä sinä voit tehdä voittojesi eteen.",
    94: "Naiset ja raha-asiat eivät sovi yhteen.",
    95: "Kasva tai kuole.",
    97: "Tarpeeksi... ei ole koskaan tarpeeksi.",
    98: "Jokaisella on hintansa.",
    99: "Luottamus on vaativin sitoumus.",
    102: "Luonto lahoaa, mutta latinum on ikuista.",
    103: "Nukkuminen voi häiritä mahdollisuutta.",
    104: "Usko siirtää vuoria... inventaariovuoria.",
    106: "Köyhyydessä ei ole kunniaa.",
    109: "Arvokkuus ja tyhjä säkki ovat säkin arvoisia.",
    111: "Kohtele velallisia kuten perhettäsi. Riistä heitä.",
    112: "Seksi pomon siskon kanssa on kielletty.",
    113: "Harrasta aina seksiä pomosi kanssa.",
    121: "Kaikki on myytävänä, jopa ystävyys.",
    123: "Jopa sokea voi huomata latinumin hohdon.",
    125: "Et voi tehdä sopimuksia, jos olet kuollut.",
    139: "Vaimot palvelevat, veljet perivät.",
    141: "Vain tyhmät maksavat jälleenmyynnistä.",
    144: "Hyväntekeväisyydessä ei ole mitään pahaa... niin kauan kuin se palautuu taskuusi.",
    162: "Jopa huonoimpina aikoina joku tekee voittoa.",
    168: "Kuiskaa tiesi menestykseen.",
    177: "Tunne vihollisesi... mutta tee heidän kanssaan aina kauppaa.",
    181: "Edes vilpillisyys ei voi himmentää voittoa.",
    189: "Anna muiden pitää maineensa. Pidä sinä heidän rahasi.",
    190: "Kuule kaikki; älä luota mihinkään.",
    192: "Älä koskaan huijaa klingonia... paitsi, jos olet varma, että pääset livohkaan.",
    194: "On aina hyväksi bisnekselle tietää, mitä asiakkaasi ajattelevat, ennen kuin he astuvat ovestasi sisään.",
    202: "Voiton oikeutus on voitto.",
    203: "Uudet asiakkaat ovat kuin terähampaisia greematoja. Ne voivat olla meheviä, mutta joskus purevat takaisin.",
    208: "Joskus ainoa kysymystä vaarallisempi asia on vastaus.",
    211: "Työntekijät ovat askelmia menestykseen johtavilla tikapuilla. Älä epäröi astua niiden päälle.",
    214: "Älä koskaan aloita liikeneuvotteluja tyhjällä vatsalla.",
    217: "Et voi vapauttaa kalaa vedestä.",
    218: "Tiedä aina, mitä olet ostamassa.",
    223: "Varo miestä, jolla ei ole aikaa oo-moxille.",
    229: "Latinum kestää kauemmin kuin himo.",
    236: "Et voi ostaa kohtaloa.",
    239: "Älä koskaan epäröi antaa tuotteelle harhaanjohtavaa nimeä.",
    242: "Enemmän on hyvä... kaikki on parempaa.",
    255: "Vaimo on luksusta... viisas tilintarkastaja taas välttämättömyys.",
    261: "Varakas mies voi ostaa kaiken paitsi omantunnon.",
    263: "Älä koskaan anna epäilyksen himmentää latinumin himoasi.",
    266: "Kun olet epäilyksen vallassa, valehtele.",
    284: "Sisimmissään jokainen on ferengi",
    285: "Hyvää tekoa ei koskaan jätetä rankaisematta.",
    286: "Kaikki on lopussa, kun Morn lähtee. (Quarkin keksimä)",
    299: "Kun käytät jotakuta hyväksesi, kannattaa muistaa kiittää. Seuraavalla kerralla on sitten "
         "helpompi hönäyttää. (Neelixin keksimä olematon sääntö)",
}

